shell = "bash -lc '{}'"

[[items]]
file = "~/.config/gtk-3.0/colors.css"
template = "gtk-3.0"
rewrite = true
hook = "pkill -SIGUSR2 waybar || true"

[[items]]
file = "~/.config/hypr/colors.conf"
template = "hyprland"  # создадим шаблон
rewrite = true
